name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  - buildpublish: BuildPublish
    displayName: 'Build and Publish'
    steps:
      - script: npm install
        displayName: 'Install Dependencies'
      - script: npm run build
        displayName: 'Build'
      - task: CopyFiles@2
        displayName: 'Copy Build Output'
        inputs:
          Contents: 'build/**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'               
      - task: PublishBuildArtifacts@1
        displayName: 'Publish to Azure Pipelines'
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: 'www'